### ISSUE TITLE
the binary may be better to put into release page

### ISSUE THREAD

**Issue by chinglinwen** [zieckey/gochart#1]

**Comment by zieckey** [comment]
Thanks for your advise.
I am so sorry to reply this issue so late. I missed it.
Can you tell me how to do it? I will be very happy if you can help me. Thank you very much.

**Comment by chinglinwen** [comment]
The following are my opinion (I don't know if others are doing this way) ( but binary are often in the release page for download)

1. Create a release on this GitHub repository, you can provide a version as tag ( eg. v1.0.0 ), there you can upload the binary (or compressed binary ).

2. Delete the binary from the git ( git remove download or git rm download , I don't remember the exact command).

3. You may want to modify the . git/info/ignore file to ignore the binary for you future commit to avoid include the binary

**Comment by zieckey** [comment]
Thanks for your help. I have released the first version. 
I release the version is `1.0` but not `v1.0`, that is a little bit pity.
I will release `v1.1` in the future.

**Comment by chinglinwen** [comment]
Great.

**Comment by zieckey** [comment]
You are always online? That's amazing. 
It is so nice to meet you here. I have followed you.
Thank you very much.

**Comment by chinglinwen** [comment]
Well, I received the new notification from my email.

**Comment by chinglinwen** [comment]
You're welcome by the way !

**Comment by zieckey** [comment]
:)
